# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mozii
service: mmmelton-backend-js

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

plugins:
  - serverless-offline

custom:
  corsDefault:
    origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "https://mmmelton.com"
    headers:
      - Api-Key
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent

  authorizerDefault:
    type: TOKEN
    name: apiAuthorizer
    identitySource: method.request.header.Api-Key

functions:
  apiAuthorizer:
    handler: auth.handler
    environment:
      API_KEY: ${env:API_KEY}

  mainFunction:
    handler: hello.main
    events:
      - http:
          path: /
          method: get
          cors: ${self:custom.corsDefault}
          authorizer: ${self:custom.authorizerDefault}

  subFunction:
    handler: hello.main
    events:
      - http:
          path: /sub
          method: get
          cors: ${self:custom.corsDefault}
          authorizer: ${self:custom.authorizerDefault}